export const getMainLayoutStyles = () => ({
  root: { height: '100vh' as const, overflow: 'hidden' as const },
  mainLayout: { flex: 1, overflow: 'hidden' as const, display: 'flex' as const },
  sider: {
    background: 'var(--background-card)',
    borderRight: '1px solid var(--border-color)',
  },
  siderContent: { display: 'flex' as const, flexDirection: 'column' as const, height: '100%' },
  searchContainer: { padding: '8px 8px 4px', flexShrink: 0 },
  searchInput: {
    borderRadius: 4,
    background: 'var(--background-card)',
  },
  connectionTreeContainer: { flex: 1, minHeight: 0, overflow: 'auto' as const, marginBottom: 0 },
  collapseButton: {
    height: 28,
    flexShrink: 0,
    background: 'var(--background-card)',
    borderTop: '1px solid var(--border-color)',
    display: 'flex' as const,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
    cursor: 'pointer' as const,
    transition: 'background 0.2s ease',
  },
  collapseButtonText: {
    color: 'var(--text-secondary)',
    fontSize: 11,
    display: 'flex' as const,
    alignItems: 'center' as const,
    gap: 4,
  },
  content: {
    flex: 1,
    background: 'var(--background)',
    margin: 0,
    marginLeft: 0,
    padding: 0,
    borderRadius: 0,
    overflow: 'hidden' as const,
    display: 'flex' as const,
    flexDirection: 'column' as const,
    minHeight: 0,
  },
  tabPanelContainer: {
    flex: 1,
    minHeight: 0,
    display: 'flex',
    flexDirection: 'column' as const,
  },
});
