import { Theme } from '@glideapps/glide-data-grid';

export const lightGlideTheme: Partial<Theme> = {
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  baseFontStyle: '12px',
  headerFontStyle: '600 12px',
  editorFontSize: '12px',
  cellHorizontalPadding: 8,
  cellVerticalPadding: 2,
  borderColor: '#E2E8F0',
  drilldownBorder: '#E2E8F0',
  accentColor: '#1E3A8A',
  accentLight: 'rgba(30, 58, 138, 0.08)',
  accentFg: '#FFFFFF',
  textDark: '#0F172A',
  textMedium: '#475569',
  textLight: '#94A3B8',
  textBubble: '#FFFFFF',
  textHeader: '#0F172A',
  textHeaderSelected: '#1E3A8A',
  bgIconHeader: '#F8FAFC',
  fgIconHeader: '#475569',
  bgHeader: '#F8FAFC',
  bgHeaderHasFocus: '#EFF6FF',
  bgHeaderHovered: '#F1F5F9',
  bgBubble: '#F1F5F9',
  bgBubbleSelected: '#DBEAFE',
  bgSearchResult: '#FEF3C7',
  bgCell: '#FFFFFF',
  bgCellMedium: '#F9FAFB',
  linkColor: '#1E3A8A',
  headerIconSize: 16,
  markerFontStyle: '11px',
  lineHeight: 20,
};

export const darkGlideTheme: Partial<Theme> = {
  fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  baseFontStyle: '12px',
  headerFontStyle: '600 12px',
  editorFontSize: '12px',
  cellHorizontalPadding: 8,
  cellVerticalPadding: 2,
  borderColor: '#1E3A5F',
  drilldownBorder: '#1E3A5F',
  accentColor: '#2563EB',
  accentLight: 'rgba(37, 99, 235, 0.15)',
  accentFg: '#FFFFFF',
  textDark: '#F1F5F9',
  textMedium: '#94A3B8',
  textLight: 'rgba(148,163,184,0.5)',
  textBubble: '#0B1426',
  textHeader: '#F1F5F9',
  textHeaderSelected: '#2563EB',
  bgIconHeader: '#0D1B2E',
  fgIconHeader: '#94A3B8',
  bgHeader: '#0D1B2E',
  bgHeaderHasFocus: '#112840',
  bgHeaderHovered: '#0F1D32',
  bgBubble: '#1E3A5F',
  bgBubbleSelected: '#112840',
  bgSearchResult: '#2A2510',
  bgCell: '#0B1426',
  bgCellMedium: '#0F1D32',
  linkColor: '#2563EB',
  headerIconSize: 16,
  markerFontStyle: '11px',
  lineHeight: 20,
};